application:
  port: 8000
  hmac_secret: supersecretcodethatyouwillneverguess
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "jon.staten@leadingagile.com"
  authorization_token: "secret-token"
  timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"
